import nock from "nock";

export const response = {
  success: true,
  message: "Course retrieved successfully",
  data: {
    id: 37,
    created_at: "2022-03-21T15:59:36.000000Z",
    updated_at: "2022-06-09T12:41:56.000000Z",
    title: "Jak zbudowane s\u0105 protezy i do czego",
    summary:
      "### Czego si\u0119 dowiesz i nauczysz?\n\n* Kurs umo\u017cliwia nabycie solidnych podstaw z zakresu rachunkowo\u015bci zar\u00f3wno pod wzgl\u0119dem teoretycznym jak i praktycznym\n* Kurs podstawy ksi\u0119gowo\u015bci przygotowuje s\u0142uchacza do pracy w dzia\u0142ach ksi\u0119gowo\u015bci\n* Kurs przygotowuje do zawodu ksi\u0119gowy, kt\u00f3ry zosta\u0142 uj\u0119ty w klasyfikacji zawod\u00f3w (kod zawodu 331301)\n\n\\\n### Do kogo skierowane jest szkolenie?\n\n* Dla pracownik\u00f3w dzia\u0142u ksi\u0119gowo\u015bci\n* Dla os\u00f3b kt\u00f3re swoj\u0105 karier\u0119 zawodow\u0105 chc\u0105 zwi\u0105za\u0107 z prac\u0105 w ksi\u0119gowo\u015bci\n* Dla os\u00f3b pracuj\u0105cych w dzia\u0142ach IT wdra\u017caj\u0105cych systemy ksi\u0119gowe\n\n\\",
    image_path: "/course/37/images/course-example-image.png",
    video_path: null,
    duration: "5 hours",
    author_id: 2,
    author: {
      id: 2,
      first_name: "Admin",
      last_name: "Kowalski",
      email: "admin@escola-lms.com",
      path_avatar: "avatars/2/avatar.png",
      interests: [],
      categories: [],
      contact: "Kontakt do mnie to blabla",
      "Terms of Service": true,
      "Privacy Policy": true,
      bio: "Praktyk z 15 letnim do\u015bwiadczeniem w zarz\u0105dzaniu zar\u00f3wno mikro jak i makro przedsi\u0119biorstwami",
      address: "Jakis adres",
    },
    authors: [
      {
        id: 2,
        first_name: "Admin",
        last_name: "Kowalski",
        email: "admin@escola-lms.com",
        path_avatar: "avatars/2/avatar.png",
        interests: [],
        categories: [],
        contact: "Kontakt do mnie to blabla",
        "Terms of Service": true,
        "Privacy Policy": true,
        bio: "Praktyk z 15 letnim do\u015bwiadczeniem w zarz\u0105dzaniu zar\u00f3wno mikro jak i makro przedsi\u0119biorstwami",
        address: "Jakis adres",
      },
    ],
    status: "published",
    subtitle: "100% online",
    language: null,
    description:
      "Kurs podstawy ksi\u0119gowo\u015bci przeznaczony jest dla os\u00f3b kt\u00f3re swoj\u0105 karier\u0119 zawodow\u0105 chc\u0105 zwi\u0105za\u0107 z prac\u0105 w ksi\u0119gowo\u015bci oraz dla os\u00f3b pracuj\u0105cych w dzia\u0142ach IT wdra\u017caj\u0105cych systemy ksi\u0119gowe. Program realizowany b\u0119dzie w oparciu o prac\u0119 na przepisach, rozwi\u0105zywaniu zada\u0144 sytuacyjnych, kazus\u00f3w i test\u00f3w. Uczestnicy szkolenia otrzymaj\u0105 wszystkie niezb\u0119dne do zaj\u0119\u0107 materia\u0142y: przepisy, materia\u0142y autorskie, zadania, testy.",
    categories: [
      {
        id: 28,
        name: "kat_17.01",
        slug: "kat-1701",
        is_active: true,
        parent_id: null,
        icon: null,
        icon_class: null,
        created_at: "2022-01-17T13:43:12.000000Z",
        updated_at: "2022-01-17T13:43:12.000000Z",
        pivot: { course_id: 37, category_id: 28 },
      },
      {
        id: 34,
        name: "Doradcy biznesowi",
        slug: "doradcy-biznesowi",
        is_active: true,
        parent_id: null,
        icon: null,
        icon_class: null,
        created_at: "2022-03-10T08:59:46.000000Z",
        updated_at: "2022-03-10T08:59:46.000000Z",
        pivot: { course_id: 37, category_id: 34 },
      },
    ],
    tags: [
      {
        id: 110,
        title: "Bestseller",
        morphable_type: "EscolaLms\\Courses\\Models\\Course",
        morphable_id: 37,
        created_at: "2022-05-27T13:47:33.000000Z",
        updated_at: "2022-05-27T13:47:33.000000Z",
      },
    ],
    level: null,
    lessons: [
      {
        id: 71,
        title: "Lekcja 1",
        summary: null,
        duration: null,
        active: true,
        order: 0,
        course_id: 37,
        topics: [
          {
            id: 671,
            title: "Temat 1",
            lesson_id: 71,
            active: true,
            preview: false,
            topicable_id: 96,
            topicable_type:
              "EscolaLms\\TopicTypes\\Models\\TopicContent\\RichText",
            summary: null,
            introduction: null,
            description: null,
            order: 1,
            json: null,
            can_skip: true,
          },
          {
            id: 672,
            title: "Aktywno\u015b\u0107",
            lesson_id: 71,
            active: true,
            preview: false,
            topicable_id: 143,
            topicable_type: "EscolaLms\\TopicTypes\\Models\\TopicContent\\H5P",
            summary: null,
            introduction: null,
            description: null,
            order: 2,
            json: null,
            can_skip: true,
          },
          {
            id: 702,
            title: "Add new title here",
            lesson_id: 71,
            active: true,
            preview: false,
            topicable_id: 154,
            topicable_type: "EscolaLms\\TopicTypes\\Models\\TopicContent\\H5P",
            summary: null,
            introduction: null,
            description: null,
            order: 6,
            json: null,
            can_skip: false,
          },
          {
            id: 691,
            title: "Add new title here",
            lesson_id: 71,
            active: true,
            preview: false,
            topicable_id: 100,
            topicable_type:
              "EscolaLms\\TopicTypes\\Models\\TopicContent\\Image",
            summary: null,
            introduction: null,
            description: null,
            order: 3,
            json: null,
            can_skip: false,
          },
          {
            id: 701,
            title: "Add new title here",
            lesson_id: 71,
            active: true,
            preview: false,
            topicable_id: 153,
            topicable_type: "EscolaLms\\TopicTypes\\Models\\TopicContent\\H5P",
            summary: "aa",
            introduction: "Test",
            description: "aa",
            order: 5,
            json: null,
            can_skip: false,
          },
          {
            id: 692,
            title: "Add new title here",
            lesson_id: 71,
            active: true,
            preview: false,
            topicable_id: 101,
            topicable_type:
              "EscolaLms\\TopicTypes\\Models\\TopicContent\\Image",
            summary: null,
            introduction: null,
            description: null,
            order: 4,
            json: null,
            can_skip: false,
          },
          {
            id: 710,
            title: "Add new title here",
            lesson_id: 71,
            active: true,
            preview: false,
            topicable_id: 106,
            topicable_type: "EscolaLms\\TopicTypes\\Models\\TopicContent\\PDF",
            summary: null,
            introduction: null,
            description: null,
            order: 7,
            json: null,
            can_skip: false,
          },
          {
            id: 712,
            title: "Add new title here",
            lesson_id: 71,
            active: true,
            preview: false,
            topicable_id: 102,
            topicable_type:
              "EscolaLms\\TopicTypes\\Models\\TopicContent\\RichText",
            summary: null,
            introduction: null,
            description: null,
            order: 8,
            json: null,
            can_skip: false,
          },
          {
            id: 713,
            title: "Add new title here",
            lesson_id: 71,
            active: true,
            preview: false,
            topicable_id: 108,
            topicable_type: "EscolaLms\\TopicTypes\\Models\\TopicContent\\PDF",
            summary: null,
            introduction: null,
            description: null,
            order: 9,
            json: null,
            can_skip: false,
          },
          {
            id: 751,
            title: "Add new title here",
            lesson_id: 71,
            active: true,
            preview: false,
            topicable_id: null,
            topicable_type: null,
            summary: null,
            introduction: null,
            description: null,
            order: 10,
            json: null,
            can_skip: false,
          },
          {
            id: 752,
            title: "Add new title here",
            lesson_id: 71,
            active: true,
            preview: false,
            topicable_id: null,
            topicable_type: null,
            summary: null,
            introduction: null,
            description: null,
            order: 11,
            json: null,
            can_skip: false,
          },
        ],
      },
      {
        id: 74,
        title: "Lekcja 1",
        summary: null,
        duration: null,
        active: true,
        order: 0,
        course_id: 37,
        topics: [
          {
            id: 705,
            title: "Add new title here",
            lesson_id: 74,
            active: true,
            preview: false,
            topicable_id: 101,
            topicable_type:
              "EscolaLms\\TopicTypes\\Models\\TopicContent\\RichText",
            summary: "wadwad",
            introduction: "awdwad",
            description: "awdwad",
            order: 3,
            json: null,
            can_skip: false,
          },
          {
            id: 706,
            title: "awdwad",
            lesson_id: 74,
            active: true,
            preview: false,
            topicable_id: 102,
            topicable_type: "EscolaLms\\TopicTypes\\Models\\TopicContent\\PDF",
            summary: null,
            introduction: null,
            description: null,
            order: 4,
            json: null,
            can_skip: false,
          },
          {
            id: 707,
            title: "awdwad",
            lesson_id: 74,
            active: true,
            preview: false,
            topicable_id: 103,
            topicable_type: "EscolaLms\\TopicTypes\\Models\\TopicContent\\PDF",
            summary: "a",
            introduction: "a",
            description: "a",
            order: 4,
            json: null,
            can_skip: false,
          },
          {
            id: 684,
            title: "Temat 1",
            lesson_id: 74,
            active: true,
            preview: false,
            topicable_id: 97,
            topicable_type:
              "EscolaLms\\TopicTypes\\Models\\TopicContent\\RichText",
            summary: null,
            introduction: null,
            description: null,
            order: 1,
            json: null,
            can_skip: true,
          },
          {
            id: 685,
            title: "Aktywno\u015b\u0107",
            lesson_id: 74,
            active: true,
            preview: false,
            topicable_id: 147,
            topicable_type: "EscolaLms\\TopicTypes\\Models\\TopicContent\\H5P",
            summary: null,
            introduction: null,
            description: null,
            order: 2,
            json: null,
            can_skip: true,
          },
          {
            id: 732,
            title: "Add new title here",
            lesson_id: 74,
            active: true,
            preview: false,
            topicable_id: 107,
            topicable_type:
              "EscolaLms\\TopicTypes\\Models\\TopicContent\\Image",
            summary: null,
            introduction: null,
            description: null,
            order: 5,
            json: null,
            can_skip: false,
          },
        ],
      },
    ],
    poster_path: null,
    active_from: "2022-03-21T00:00:00.000000Z",
    active_to: "2026-06-27T00:00:00.000000Z",
    hours_to_complete: 10,
    findable: true,
    scorm_sco_id: null,
    target_group: null,
    users_count: 6,
    image_url:
      "https://api-stage.escolalms.com//storage/course/37/images/course-example-image.png",
    video_url: null,
    poster_url: null,
    teaser_url: null,
    product: {
      id: 43,
      type: "single",
      name: "Nowy Kurs",
      description: null,
      price: 200,
      price_old: null,
      tax_rate: 23,
      extra_fees: 0,
      purchasable: true,
      duration: null,
      calculated_duration: 0,
      limit_per_user: 1,
      limit_total: null,
      productables: [
        {
          id: 37,
          morph_class: "EscolaLms\\Courses\\Models\\Course",
          productable_id: 37,
          productable_type: "App\\Models\\Course",
          quantity: 1,
          name: "Jak zbudowane s\u0105 protezy i do czego",
          description:
            "Kurs podstawy ksi\u0119gowo\u015bci przeznaczony jest dla os\u00f3b kt\u00f3re swoj\u0105 karier\u0119 zawodow\u0105 chc\u0105 zwi\u0105za\u0107 z prac\u0105 w ksi\u0119gowo\u015bci oraz dla os\u00f3b pracuj\u0105cych w dzia\u0142ach IT wdra\u017caj\u0105cych systemy ksi\u0119gowe. Program realizowany b\u0119dzie w oparciu o prac\u0119 na przepisach, rozwi\u0105zywaniu zada\u0144 sytuacyjnych, kazus\u00f3w i test\u00f3w. Uczestnicy szkolenia otrzymaj\u0105 wszystkie niezb\u0119dne do zaj\u0119\u0107 materia\u0142y: przepisy, materia\u0142y autorskie, zadania, testy.",
        },
      ],
      teaser_url: null,
      poster_path:
        "products/43/posters/X8UXQUJoRHiLFhoo4IgqO3sPA7ziZbvFMZQlWzKw.png",
      poster_url:
        "https://api-stage.escolalms.com//storage/products/43/posters/X8UXQUJoRHiLFhoo4IgqO3sPA7ziZbvFMZQlWzKw.png",
      buyable: false,
      owned: false,
      categories: [],
      tags: [],
      updated_at: "2022-05-27T13:43:01.000000Z",
      authors: [
        {
          id: 2,
          first_name: "Admin",
          last_name: "Kowalski",
          email: "admin@escola-lms.com",
          phone: null,
          is_active: true,
          email_verified_at: "2021-10-14 15:50:26",
          path_avatar: "avatars/2/avatar.png",
          gender: null,
          age: null,
          country: null,
          city: null,
          street: null,
          postcode: null,
          created_at: "2021-10-14T15:50:26.000000Z",
          updated_at: "2022-06-27T16:17:32.000000Z",
          points: 0,
          notification_channels: "null",
          access_to_directories:
            '["course\\/42","course\\/43","course\\/44","course\\/45","course\\/46","course\\/49","course\\/50","course\\/51","course\\/53","course\\/54","course\\/56"]',
          current_timezone: "UTC",
          deleted_at: null,
          avatar_url:
            "https://api-stage.escolalms.com//storage/avatars/2/avatar.png",
          contact: "Kontakt do mnie to blabla",
          "Terms of Service": true,
          "Privacy Policy": true,
          bio: "Praktyk z 15 letnim do\u015bwiadczeniem w zarz\u0105dzaniu zar\u00f3wno mikro jak i makro przedsi\u0119biorstwami",
          address: "Jakis adres",
          pivot: { course_id: 37, author_id: 2 },
          categories: [],
        },
      ],
      related_products: [],
    },
    related_product: null,
  },
};

export default (scope: nock.Scope) =>
  scope.get("/api/courses/1").reply(200, response);
