import nock from "nock";

export const response = {
  success: true,
  data: [
    {
      id: 20,
      created_at: "2022-04-03T09:49:47.000000Z",
      updated_at: "2022-04-03T09:49:52.000000Z",
      active_from: "2022-04-03T08:15:00.000000Z",
      active_to: "2022-04-03T09:15:00.000000Z",
      name: "Testowy webinar233",
      status: "published",
      description: "Aut distinctio mollitia ut ut minima et fugiat.",
      short_desc: null,
      agenda: null,
      duration: "2 hours",
      trainers: [
        {
          id: 2,
          first_name: "Admin",
          last_name: "Kowalski",
          email: "admin@escola-lms.com",
          phone: null,
          is_active: true,
          email_verified_at: "2021-10-14 15:50:26",
          path_avatar: "avatars/2/avatar.png",
          gender: null,
          age: null,
          country: null,
          city: null,
          street: null,
          postcode: null,
          created_at: "2021-10-14T15:50:26.000000Z",
          updated_at: "2022-07-06T14:31:32.000000Z",
          points: 0,
          notification_channels: "null",
          access_to_directories:
            '["course\\/42","course\\/43","course\\/44","course\\/45","course\\/46","course\\/49","course\\/50","course\\/51","course\\/53","course\\/54","course\\/56","course\\/57","course\\/58","course\\/59","course\\/60","course\\/61","course\\/62","course\\/65","course\\/66","course\\/67","course\\/68","course\\/69","course\\/70","course\\/71"]',
          current_timezone: "UTC",
          deleted_at: null,
          avatar_url:
            "https://api-stage.escolalms.com//storage/avatars/2/avatar.png",
          contact: "Kontakt do mnie to blabla...",
          "Privacy Policy": true,
          bio: "Praktyk z 15 letnim doświadczeniem w zarządzaniu zarówno mikro jak i makro przedsiębiorstwami...",
          address: "Jakis adres...",
          "Terms of Service": true,
          pivot: {
            webinar_id: 20,
            trainer_id: 2,
          },
        },
      ],
      image_path: null,
      image_url: "",
      logotype_path: null,
      logotype_url: "",
      yt_url:
        "https://www.youtube.com/embed/gdFhrNGf2Ow?autoplay=1&livemonitor=1",
      tags: [],
      product: null,
      in_coming: false,
      is_ended: true,
      is_started: false,
    },
    {
      id: 22,
      created_at: "2022-04-04T07:24:48.000000Z",
      updated_at: "2022-04-04T07:24:54.000000Z",
      active_from: "2022-04-03T08:15:00.000000Z",
      active_to: "2022-04-03T09:15:00.000000Z",
      name: "Testowy webinar288",
      status: "published",
      description: "Aut distinctio mollitia ut ut minima et fugiat.",
      short_desc: null,
      agenda: null,
      duration: "2 hours",
      trainers: [
        {
          id: 2,
          first_name: "Admin",
          last_name: "Kowalski",
          email: "admin@escola-lms.com",
          phone: null,
          is_active: true,
          email_verified_at: "2021-10-14 15:50:26",
          path_avatar: "avatars/2/avatar.png",
          gender: null,
          age: null,
          country: null,
          city: null,
          street: null,
          postcode: null,
          created_at: "2021-10-14T15:50:26.000000Z",
          updated_at: "2022-07-06T14:31:32.000000Z",
          points: 0,
          notification_channels: "null",
          access_to_directories:
            '["course\\/42","course\\/43","course\\/44","course\\/45","course\\/46","course\\/49","course\\/50","course\\/51","course\\/53","course\\/54","course\\/56","course\\/57","course\\/58","course\\/59","course\\/60","course\\/61","course\\/62","course\\/65","course\\/66","course\\/67","course\\/68","course\\/69","course\\/70","course\\/71"]',
          current_timezone: "UTC",
          deleted_at: null,
          avatar_url:
            "https://api-stage.escolalms.com//storage/avatars/2/avatar.png",
          contact: "Kontakt do mnie to blabla...",
          "Privacy Policy": true,
          bio: "Praktyk z 15 letnim doświadczeniem w zarządzaniu zarówno mikro jak i makro przedsiębiorstwami...",
          address: "Jakis adres...",
          "Terms of Service": true,
          pivot: {
            webinar_id: 22,
            trainer_id: 2,
          },
        },
      ],
      image_path: null,
      image_url: "",
      logotype_path: null,
      logotype_url: "",
      yt_url:
        "https://www.youtube.com/embed/nivfbw3P2P4?autoplay=1&livemonitor=1",
      tags: [],
      product: null,
      in_coming: false,
      is_ended: true,
      is_started: false,
    },
    {
      id: 25,
      created_at: "2022-04-06T18:09:38.000000Z",
      updated_at: "2022-04-06T18:24:44.000000Z",
      active_from: "2022-04-06T06:24:37.000000Z",
      active_to: "2022-04-06T18:24:32.000000Z",
      name: "sratatatatata",
      status: "published",
      description: "wadwad",
      short_desc: "dawwad",
      agenda: "wadwad",
      duration: "2 hours",
      trainers: [
        {
          id: 174,
          first_name: "Mateusz",
          last_name: "Tutor",
          email: "testowytutor@test.com",
          phone: "123456789",
          is_active: true,
          email_verified_at: "2022-03-29 11:12:43",
          path_avatar: null,
          gender: null,
          age: null,
          country: null,
          city: null,
          street: null,
          postcode: null,
          created_at: "2022-03-29T10:51:38.000000Z",
          updated_at: "2022-04-15T09:27:45.000000Z",
          points: 0,
          notification_channels: "null",
          access_to_directories: '["webinar\\/27"]',
          current_timezone: "UTC",
          deleted_at: null,
          avatar_url: null,
          contact: "PL",
          address: "PL",
          "Terms of Service": true,
          "Privacy Policy": true,
          bio: "PL",
          pivot: {
            webinar_id: 25,
            trainer_id: 174,
          },
        },
      ],
      image_path:
        "/webinar/25/images/cRRS1PQErDFAHaqmAnLYCH5IpqwEMebd0VFmLvO3.jpg",
      image_url:
        "https://api-stage.escolalms.com//storage/webinar/25/images/cRRS1PQErDFAHaqmAnLYCH5IpqwEMebd0VFmLvO3.jpg",
      logotype_path: null,
      logotype_url: "",
      yt_url:
        "https://www.youtube.com/embed/JfHiYi5xcdI?autoplay=1&livemonitor=1",
      tags: [],
      product: null,
      in_coming: false,
      is_ended: true,
      is_started: false,
    },
    {
      id: 5,
      created_at: "2022-03-08T11:03:31.000000Z",
      updated_at: "2022-03-08T11:04:12.000000Z",
      active_from: "2022-03-08T00:00:00.000000Z",
      active_to: "2022-03-31T00:00:00.000000Z",
      name: "awdwadwad",
      status: "published",
      description: "awdwad",
      short_desc: null,
      agenda: null,
      duration: "22",
      trainers: [
        {
          id: 15,
          first_name: "Daytona",
          last_name: "600",
          email: "summer67@example.com",
          phone: null,
          is_active: true,
          email_verified_at: "2021-10-14 15:50:27",
          path_avatar:
            "avatars/15/vCQVX6MiBpWFDlwn0j30D9M95tqtQdjuoiuTfOSO.jpg",
          gender: null,
          age: null,
          country: null,
          city: null,
          street: null,
          postcode: null,
          created_at: "2021-10-14T15:50:28.000000Z",
          updated_at: "2022-03-14T12:47:50.000000Z",
          points: 0,
          notification_channels: "null",
          access_to_directories: null,
          current_timezone: "UTC",
          deleted_at: null,
          avatar_url:
            "https://api-stage.escolalms.com//storage/avatars/15/vCQVX6MiBpWFDlwn0j30D9M95tqtQdjuoiuTfOSO.jpg",
          contact: '""',
          pivot: {
            webinar_id: 5,
            trainer_id: 15,
          },
        },
        {
          id: 18,
          first_name: "Nelda",
          last_name: "Gusikowski",
          email: "collins.velma@example.net",
          phone: null,
          is_active: true,
          email_verified_at: "2021-10-14 15:50:27",
          path_avatar: "avatars/18/photo-1642880384912-2cd8371979b1.jpeg",
          gender: null,
          age: null,
          country: null,
          city: null,
          street: null,
          postcode: null,
          created_at: "2021-10-14T15:50:28.000000Z",
          updated_at: "2022-03-14T15:33:53.000000Z",
          points: 0,
          notification_channels: "null",
          access_to_directories: null,
          current_timezone: "UTC",
          deleted_at: null,
          avatar_url:
            "https://api-stage.escolalms.com//storage/avatars/18/photo-1642880384912-2cd8371979b1.jpeg",
          contact: '""',
          "Terms of Service": true,
          "Privacy Policy": true,
          address: "cedrowa 2/22",
          pivot: {
            webinar_id: 5,
            trainer_id: 18,
          },
        },
        {
          id: 21,
          first_name: "Ottoo",
          last_name: "Mueller",
          email: "garrick81@example.net",
          phone: null,
          is_active: true,
          email_verified_at: "2021-10-14 15:50:27",
          path_avatar: "avatars/21/1.jpg",
          gender: null,
          age: null,
          country: null,
          city: null,
          street: null,
          postcode: null,
          created_at: "2021-10-14T15:50:28.000000Z",
          updated_at: "2022-03-23T13:41:13.000000Z",
          points: 0,
          notification_channels: "null",
          access_to_directories: null,
          current_timezone: "UTC",
          deleted_at: null,
          avatar_url:
            "https://api-stage.escolalms.com//storage/avatars/21/1.jpg",
          contact: '""',
          address: '""',
          "Terms of Service": true,
          "Privacy Policy": true,
          pivot: {
            webinar_id: 5,
            trainer_id: 21,
          },
        },
      ],
      image_path: "/",
      image_url: "",
      logotype_path: null,
      logotype_url: "",
      yt_url: null,
      tags: [],
      product: null,
      in_coming: false,
      is_ended: true,
      is_started: false,
    },
  ],
  meta: {
    current_page: 1,
    first_page_url: "http://api-stage.escolalms.com/api/webinars?page=1",
    from: 1,
    last_page: 5,
    last_page_url: "http://api-stage.escolalms.com/api/webinars?page=5",
    links: [
      {
        url: null,
        label: "&laquo; Previous",
        active: false,
      },
      {
        url: "http://api-stage.escolalms.com/api/webinars?page=1",
        label: "1",
        active: true,
      },
      {
        url: "http://api-stage.escolalms.com/api/webinars?page=2",
        label: "2",
        active: false,
      },
      {
        url: "http://api-stage.escolalms.com/api/webinars?page=3",
        label: "3",
        active: false,
      },
      {
        url: "http://api-stage.escolalms.com/api/webinars?page=4",
        label: "4",
        active: false,
      },
      {
        url: "http://api-stage.escolalms.com/api/webinars?page=5",
        label: "5",
        active: false,
      },
      {
        url: "http://api-stage.escolalms.com/api/webinars?page=2",
        label: "Next &raquo;",
        active: false,
      },
    ],
    next_page_url: "http://api-stage.escolalms.com/api/webinars?page=2",
    path: "http://api-stage.escolalms.com/api/webinars",
    per_page: "4",
    prev_page_url: null,
    to: 4,
    total: 20,
  },
  message: "Webinars retrieved successfully",
};

export default (scope: nock.Scope) =>
  scope.get("/api/webinars").reply(200, response);
